const REPO_OWNER="lyode";
const REPO_NAME="refitinterior";
const ASSET_API=`https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/assets`;
const IMAGE_EXT=/\.(jpg|jpeg|png|webp|gif)$/i;
const EXCLUDE=/(logo|wordmark|favicon|placeholder|incometax|400px|800px|used copy|new logo|cad)/i;
const FALLBACK_IMAGES=["project-commercial-1.jpg","project-commercial-2.jpg","project-commercial-3.jpg","project-residential-1.jpg","project-residential-2.jpg"].map(name=>({name,url:`assets/${encodeURIComponent(name)}`,type:"file"}));
function cleanTitle(name){return name.replace(/\.[^.]+$/," ").replace(/^\d+[\s._-]*/,"").replace(/[-_]+/g," ").replace(/\s+/g," ").trim().replace(/\b\w/g,c=>c.toUpperCase())||"REFIT Project"}
function detectCategory(name){const n=name.toLowerCase();if(/(cafe|restaurant|fnb|food|beverage|bar|kitchen)/.test(n))return{key:"fnb",label:"F&B"};if(/(residential|home|house|condo|apartment|living|bedroom|bathroom)/.test(n))return{key:"residential",label:"Residential"};if(/(commercial|office|retail|shop|showroom|studio|workspace)/.test(n))return{key:"commercial",label:"Commercial"};if(/(maintenance|repair|defect|after|before|upgrade|improvement)/.test(n))return{key:"maintenance",label:"Maintenance"};if(/(3d|render|concept|drawing|layout|plan)/.test(n))return{key:"concept",label:"Concept"};return{key:"project",label:"Project"}}
async function getAssetImages(){try{const res=await fetch(ASSET_API,{cache:"no-store"});if(!res.ok)throw new Error("Cannot read assets folder");const data=await res.json();const images=data.filter(item=>item.type==="file"&&IMAGE_EXT.test(item.name)&&!EXCLUDE.test(item.name)).map(item=>({name:item.name,url:item.download_url||`assets/${encodeURIComponent(item.name)}`,title:cleanTitle(item.name),...detectCategory(item.name)}));return images.length?images:FALLBACK_IMAGES.map(i=>({...i,title:cleanTitle(i.name),...detectCategory(i.name)}))}catch(error){return FALLBACK_IMAGES.map(i=>({...i,title:cleanTitle(i.name),...detectCategory(i.name)}))}}
function setupMenu(){const menuBtn=document.getElementById("menuBtn");const navLinks=document.getElementById("navLinks");if(!menuBtn||!navLinks)return;menuBtn.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});navLinks.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{navLinks.classList.remove("open");menuBtn.setAttribute("aria-expanded","false")}))}
function setupReveal(){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")})},{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el))}
function setupWhatsappForm(){const form=document.getElementById("interestForm");if(!form)return;form.addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("name").value.trim();const company=document.getElementById("company").value.trim();const product=document.getElementById("product").value;const message=document.getElementById("message").value.trim();const text=`Hello REFIT, I am ${name}${company?" from "+company:""}. I am interested in ${product}.${message?"\n\nProject / request: "+message:""}`;window.open("https://wa.me/60122145922?text="+encodeURIComponent(text),"_blank","noopener")})}
